name: 'Update Documentation'
description: 'Action for automatic documentation updates'

inputs:
  path:
    description: "Path where searching files"
    required: false
  ext:
    description: "File extension to match"
    required: false

outputs:
  files:
    value: ${{ steps.files.outputs.files }}
    description: "List of all matching files"
  dirs:
    value: ${{ steps.dirs.outputs.dirs }}
    description: "List of all matching files"

runs:
  using: "composite"
  steps:
  - name: Get files
    id: files
    run: echo "files=$(basename -a $(ls ${{ inputs.path }}/*.${{ inputs.ext }}) | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
    shell: bash

  - name: Get dirs
    id: dirs
    run: echo "dirs=$(basename -a $(ls -d ${{ inputs.path }}/*/) | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
    shell: bash

