name: 'Update Documentation'
description: 'Action for automatic documentation updates'

inputs:
  path:
    description: "Path where searching files"
    required: false
  ext:
    description: "File extension to match"
    required: false
outputs:
  files:
    value: ${{ steps.files.outputs.files }}
    description: "List of all matching files"

runs:
  using: "composite"
  steps:
  - name: Get files in 
    id: files
    run: |
      files=`ls ${{ inputs.path }}/*.${{ inputs.ext }}`
      echo "Files: $files"
      echo "files=$files >> "$GITHUB_OUTPUT"
      # for eachfile in $files
      # # do
      # #    echo $eachfile
      # #    echo "files=$eachfile" >> "$GITHUB_OUTPUT"
      # # done
    shell: bash




