name: 'Update Documentation'
description: 'Action for automatic documentation updates'

inputs:
  path:
    description: "Path where searching files"
    required: false
  ext:
    description: "File extension to match"
    required: false

outputs:
  files:
    value: ${{ steps.files.outputs.files }}
    description: "List of all matching files"

runs:
  using: "composite"
  steps:
  - name: Get files 
    id: files
    run: echo "files=$(ls ${{ inputs.path }}" >> $GITHUB_OUTPUT
    shell: bash




