name: 'Action for Terraform'
description: 'Action for terraform'

inputs:
  TF_DIR:
    description: 'relative path to terraform root dir'
    required: true
  GITHUB_TOKEN:
    description: 'GITHUB Token for terraform init'
    required: true
  TERRAFORM_ACTION:
    description: 'Terraform Action to execute'
    required: false  
    default: 'version'
  TF_VARS_FILE:
    description: 'tfvars file'
    required: false
  OTC_TF_VARS_FILE:
    description: 'tfvars file'
    required: false
  CLOUD_REGION:
    description: 'AWS Region, Azure location, GCP location for deployment'
    required: false
    default: 'default'
  GCP_PROJECT_ID:
    description: 'Google project_id'
    required: false
    default: 'otc-plattform'
  TF_PARTIAL_BACKEND_FILE:
    description: 'Partial backend file'
    required: false
    default: ''
  BACKEND_DESTROY:
    description: 'Destroy Backend'
    required: false
    default: 'false'
    
runs:
  using: "composite"
  steps:

    - name: terraform Action
      run: "bash ${{ github.action_path }}/scripts/terraform.sh"
      shell: bash
      env:
        TF_DIR: ${{ inputs.TF_DIR }}
        TERRAFORM_ACTION: ${{ inputs.TERRAFORM_ACTION }}
        TF_PARTIAL_BACKEND_FILE: ${{ inputs.TF_PARTIAL_BACKEND_FILE }}
        BACKEND_DESTROY: ${{ inputs.BACKEND_DESTROY }}
        TF_VARS_FILE: ${{ inputs.TF_VARS_FILE }}
        OTC_TF_VARS_FILE: ${{ inputs.TF_VARS_FILE }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        CLOUD_REGION: ${{ inputs.CLOUD_REGION }}
        GCP_PROJECT_ID: ${{ inputs.GCP_PROJECT_ID }}



