name: 'Update Documentation'
description: 'Action for automatic documentation updates'

inputs:
  TF_DIR:
    description: 'Working directory for action'
    required: true
  GITHUB_TOKEN:
    description: 'GITHUB Token'
    required: true

runs:
  using: "composite"
  steps:

    - name: Update Docs
      run: "bash ${{ github.action_path }}/scripts/readme.sh"
      shell: bash
      env:
        FILE: '${{ inputs.TF_DIR}}/README.md'
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
