name: OTC Test - docs
on:
  workflow_dispatch:
  pull_request:
  release:
    types: [published]
on:

  push:
    branches:
      - '*'
permissions:
  contents: write


jobs:
  test:
    name: OTC test - docs
    environment: dev
    runs-on: [Linux]
    steps:
      - uses: actions/checkout@v3
      - name: Environment
        run: "export"
        shell: bash
      # - name: Test - ToC
      #   uses: ./docs/
      #   with:
      #     TF_DIR: '${{ github.workspace }}/test/terraform'
