name: OTC Test - docs
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'

permissions:
  contents: write


jobs:
  test:
    name: OTC test - docs
    environment: dev
    runs-on: [Linux]
    steps:
      - uses: actions/checkout@v3
      - name: Test - ToC
        uses: ./docs/
        with:
          TF_DIR: '${{ github.workspace }}/test/terraform'
