name: OTC Test - docs
on:
  workflow_dispatch:
  pull_request:
  release:
    types: [published]
  push:
    branches:
      - '*'


jobs:
  test:
    name: OTC test - docs
    environment: dev
    runs-on: [Linux]
    steps:
      - name: Environment
        run: "export"
        shell: bash
      - name: Test - Docs
        uses: ./docs/
        with:
          TF_DIR: '${{ github.workspace }}/test/docs'
