name: OTC Test - helper
on:
  workflow_dispatch:
  push:
  #   branches:
  #     - '**'
  #     - '!main'


permissions:
  contents: read

jobs:
  test:
    name: OTC test - docs
    environment: INT
    runs-on: [Linux]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: export
      - name: Test - Helper
        uses: ./helper/
        with:
          path: '${{ github.workspace }}/test/terraform/tfvars'
          ext: 'tfvars'