name: OTC Test - helper
on:
  workflow_dispatch:
  push:
  #   branches:
  #     - '**'
  #     - '!main'


permissions:
  contents: read

jobs:
  test:
    name: OTC test - helper
    environment: INT
    runs-on: [Linux]
    steps:
      - uses: actions/checkout@v3
      - name: Test - Helper
        uses: ./helper/
        with:
          path: '${{ github.workspace }}/test/terraform/tfvars'
          ext: 'tfvars'

  outputs:
    name: OTC test outputs - helper
    environment: INT
    runs-on: [Linux]
    # strategy:
    #   matrix:
    #     file: ${{ needs.test.outputs.files }}
    needs: test
    steps:
      - name: Test
        env:
         OUTPUT: ${{matrix.file}}
        run: echo ${{ needs.test.outputs.files }}