name: OTC Test - helper
on:
  workflow_dispatch:
  push:
  #   branches:
  #     - '**'
  #     - '!main'


permissions:
  contents: read

jobs:
  test:
    name: OTC test - helper
    environment: INT
    runs-on: [Linux]
    outputs:
      files: ${{ steps.files.outputs.files }}
      dirs: ${{ steps.files.outputs.dirs }}
    steps:
      - uses: actions/checkout@v3
      - name: Test - Helper
        id: files
        uses: ./helper/
        with:
          path: '${{ github.workspace }}/test/terraform/tfvars'
          ext: 'tfvars'

  outputs:
    name: OTC test outputs - helper
    environment: INT
    runs-on: [Linux]
    # strategy:
    #   matrix:
    #     file: ${{ fromjson(needs.test.outputs.files) }}
    needs: test
    steps:
      - name: Test
        env:
         OUTPUT: ${{matrix.file}}
        run: |
          echo ${{ needs.test.outputs.files }}
          echo ${{ needs.test.outputs.dirs }}