name: OTC Test - Release
on:
  push:
    branches:
      - 'main'

# permissions:
#   contents: write

jobs:
  test:
    name: OTC test - Release
    environment: dev
    runs-on: [Linux]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: export
      # - name: Test - Docs
      #   uses: ./docs/
      #   with:
      #     TF_DIR: '${{ github.workspace }}/test/docs'
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 16
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branches: ['main']


      # - name: "Determine tag"
      #   run: "echo \"RELEASE_TAG=${GITHUB_REF#refs/tags/}\" >> $GITHUB_ENV"
      # - name: "Create release"
      #   uses: "actions/github-script@v6"
      #   with:
      #     github-token: "${{ secrets.GITHUB_TOKEN }}"
      #     script: |
      #       try {
      #         const response = await github.rest.repos.createRelease({
      #           draft: false,
      #           generate_release_notes: true,
      #           name: process.env.RELEASE_TAG,
      #           owner: context.repo.owner,
      #           prerelease: false,
      #           repo: context.repo.repo,
      #           tag_name: process.env.RELEASE_TAG,
      #         });
      # 
      #         core.exportVariable('RELEASE_ID', response.data.id);
      #         core.exportVariable('RELEASE_UPLOAD_URL', response.data.upload_url);
      #       } catch (error) {
      #         core.setFailed(error.message);
      #       }